export const message = {
  createUser: 'User created successfully.',
  userExists: 'User already exists.',
  updateUser: 'User updated successfully.',
  noUser: 'No user found.',
  unauthorizedUser: 'Unauthorized user.',
  userFound: 'User found successfully.',
  deleteUser: 'User deleted successfully.',
  invalidCredentials: 'Invalid email or password.',
  serverError: 'Internal server error.',
  login: 'Login successful!',
  createPost: 'Post created successfully!',
  getBlog: 'Blog retrieved successfully.',
  blogNotFound: 'Blog not found.',
  imageRequired: "Image is required.",
  googleAuthInitiated: "Google authentication initiated.",
  methodNotImplemented: "Method not implemented.",
  googleAuthRedirectError: "Google Auth Redirect Error.",
  googleAuthFailed: "Authentication failed. No user data received from Google."
};
